name: Extension

on:
  workflow_dispatch:

jobs:
  extension:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        touch ~/.ssh/known_hosts
        ssh-keyscan ${{ secrets.NODE_HOST }} >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent)

    - name: Substitute environment variables
      env:
        FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
        FF_JWT_ISSUER: ${{ secrets.FF_JWT_ISSUER }}
        FF_JWT_SECRET: ${{ secrets.FF_JWT_SECRET }}
        CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
        CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
        CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
      run: |
        echo "FIREFOX_EXTENSION_ID=${FIREFOX_EXTENSION_ID}" > extension.txt
        echo "FF_JWT_ISSUER=${FF_JWT_ISSUER}" >> extension.txt
        echo "FF_JWT_SECRET=${FF_JWT_SECRET}" >> extension.txt
        echo "CHROME_EXTENSION_ID=${CHROME_EXTENSION_ID}" >> extension.txt
        echo "CHROME_CLIENT_ID=${CHROME_CLIENT_ID}" >> extension.txt
        echo "CHROME_REFRESH_TOKEN=${CHROME_REFRESH_TOKEN}" >> extension.txt
        envsubst < extension.txt > extension_fill.txt 
        
    - name: Copy files to the server
      run: |
        scp extension_fill.txt ${{ secrets.NODE_USER }}@${{ secrets.NODE_HOST }}:/opt
